"""Replay operator names."""

ADD_EVENT = "ADD_EVENT"
MERGE_EVENT = "MERGE_EVENT"
UPDATE_SLOT = "UPDATE_SLOT"
MARK_CONFLICT = "MARK_CONFLICT"
VERSION_LOG = "VERSION_LOG"

TARGET_OPERATORS = {MERGE_EVENT, UPDATE_SLOT, MARK_CONFLICT}
APPLIED_OPERATORS = {ADD_EVENT, MERGE_EVENT, UPDATE_SLOT, MARK_CONFLICT}
