"""Allowed update operators for the Stage 02 prototype."""

ADD_EVENT = "ADD_EVENT"
MERGE_EVENT = "MERGE_EVENT"
UPDATE_SLOT = "UPDATE_SLOT"
MARK_CONFLICT = "MARK_CONFLICT"
VERSION_LOG = "VERSION_LOG"

ALLOWED_OPERATORS = {
    ADD_EVENT,
    MERGE_EVENT,
    UPDATE_SLOT,
    MARK_CONFLICT,
    VERSION_LOG,
}

